config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :daily_cashes
  resources :pre_sale_products
  resources :pre_sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :street_jobs
  resources :clients
  resources :products
  resources :distributors

  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @pre_sales_receive_today = PreSale.receive_today.order(:receive_pre_sale_at)
    @pre_sales_send_today = PreSale.send_today.order(:send_pre_sale_at)
    @street_jobs_today = StreetJob.where("status IS NULL AND scheduled_at <= ?", Date.today.end_of_day).order(:scheduled_at)
    @sales_today = Sale.where(sell_at: Date.today)
    @sales_yesterday = Sale.where(sell_at: Date.yesterday)
    @sales_week = Sale.where(sell_at: Date.today.beginning_of_week..Date.today.end_of_week.end_of_day)
    @daily_cashes = DailyCash.where("created_at >= ?", Date.today.beginning_of_day)
    @daily_cashes_yesterday = DailyCash.where(created_at: Date.yesterday.beginning_of_day..Date.yesterday.end_of_day)
    @daily_cashes_week = DailyCash.where(created_at: Date.today.beginning_of_week.beginning_of_day..Date.today.end_of_week.end_of_day)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_daily_cashes.html.erb
<hr />
<h3><%= title %></h3>
<div class="well">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= DailyCash.human_attribute_name(:id) %></th>
        <th><%= DailyCash.human_attribute_name(:sale_id) %></th>
        <th><%= DailyCash.human_attribute_name(:receive_type) %></th>
        <th><%= DailyCash.human_attribute_name(:amount) %></th>
        <th><%= DailyCash.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% daily_cashes.each do |daily_cash| %>
        <tr>
          <td><%= link_to daily_cash.id, daily_cash_path(daily_cash) %></td>
          <td><%= daily_cash.sale.try(:name) %></td>
          <td><%= daily_cash_receive_type daily_cash.receive_type %></td>
          <td><%= daily_cash.amount %></td>
          <td><%=l daily_cash.created_at, format: :long %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_daily_cash_path(daily_cash), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/_sales.html.erb
<hr />
<h3><%= title %></h3>
<div class="well">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= Sale.human_attribute_name(:id) %></th>
        <th><%= Sale.human_attribute_name(:client_id) %></th>
        <th><%= Sale.human_attribute_name(:payment_method) %></th>
        <th><%= Sale.human_attribute_name(:payment_division) %></th>
        <th><%= Sale.human_attribute_name(:payment_division_sell_price) %></th>
        <th><%= Sale.human_attribute_name(:discount) %></th>
        <th><%= Sale.human_attribute_name(:status) %></th>
        <th><%= Sale.human_attribute_name(:amount_sold) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% sales.each do |sale| %>
        <tr class="<%= sale_tr_class(sale) %>">
          <td><%= link_to sale.id, sale_path(sale) %></td>
          <td><%= sale.client.name %></td>
          <td><%= sale_payment_method sale.payment_method %></td>
          <td><%= sale.payment_division %></td>
          <td><%= sale.payment_division_sell_price %></td>
          <td><%= sale.discount %></td>
          <td><%= sale_status sale.status %></td>
          <td><u><strong><%= sale.amount_sold %></strong></u></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_sale_path(sale), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/index.html.erb
<div class="page-header">
  <h1>Resumo de Operações</h1>
</div>

<h3>Peças em condicional com os clientes para pegar HOJE</h3>
<div class="well">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= PreSale.human_attribute_name(:id) %></th>
      <th><%= PreSale.human_attribute_name(:client_id) %></th>
      <th><%= PreSale.human_attribute_name(:receive_pre_sale_at) %></th>
      <th><%= PreSale.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pre_sales_receive_today.each do |pre_sale| %>
      <tr class="<%= 'danger' if pre_sale.receive_pre_sale_at < Date.today %>">
        <td><%= link_to pre_sale.id, pre_sale_path(pre_sale) %></td>
        <td><%= pre_sale.client.name %></td>
        <td><u><strong><%=l pre_sale.receive_pre_sale_at, format: :long %></strong></u></td>
        <td>
        <%= pre_sale_status pre_sale.status %>
        <% if pre_sale.receive_pre_sale_at < Date.today %>
        <strong>Atrasado</strong>
        <% end -%>
        </td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      pre_sale, :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<hr />
<h3>Levar condicional para os clientes HOJE</h3>
<div class="well">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= PreSale.human_attribute_name(:id) %></th>
        <th><%= PreSale.human_attribute_name(:client_id) %></th>
        <th><%= PreSale.human_attribute_name(:send_pre_sale_at) %></th>
        <th><%= PreSale.human_attribute_name(:status) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @pre_sales_send_today.each do |pre_sale| %>
        <tr class="<%= 'danger' if pre_sale.send_pre_sale_at < Date.today.end_of_day %>">
          <td><%= link_to pre_sale.id, pre_sale_path(pre_sale) %></td>
          <td><%= pre_sale.client.name %></td>
          <td><u><strong><%=l pre_sale.send_pre_sale_at, format: :long %></strong></u></td>
          <td>
          <%= pre_sale_status pre_sale.status %>
          <% if pre_sale.send_pre_sale_at < Date.today.end_of_day %>
          <strong>Atrasado</strong>
          <% end -%>
          </td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        pre_sale, :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<hr />
<h3>Tarefas de rua para hoje</h3>
  <div class="well">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= StreetJob.human_attribute_name(:id) %></th>
        <th><%= StreetJob.human_attribute_name(:status) %></th>
        <th><%= StreetJob.human_attribute_name(:operation_type) %></th>
        <th><%= StreetJob.human_attribute_name(:scheduled_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @street_jobs_today.each do |street_job| %>
        <tr>
          <td><%= link_to street_job.id, street_job_path(street_job) %></td>
          <td><%= street_job_status street_job.status %></td>
          <td><%= street_job_operation_type street_job.operation_type %></td>
          <td><u><strong><%=l street_job.scheduled_at, format: :long %></strong></u></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_street_job_path(street_job), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>



<div class="well">
  <h2>Vendas</h2>
  <%= render partial: "sales", locals: {sales: @sales_today, title: "Hoje: #{@sales_today.to_a.sum{|t| t.amount_sold}}"} %>
  <%= render partial: "sales", locals: {sales: @sales_yesterday, title: "Ontem: #{@sales_yesterday.to_a.sum{|t| t.amount_sold}}"} %>
  <%= render partial: "sales", locals: {sales: @sales_week, title: "Semana: #{@sales_week.to_a.sum{|t| t.amount_sold}}"} %>
</div>

<div class="well">
  <h2>Caixas</h2>
  <%= render partial: "daily_cashes", locals: {daily_cashes: @daily_cashes, title: "Hoje: #{@daily_cashes.sum(:amount)}"} %>
  <%= render partial: "daily_cashes", locals: {daily_cashes: @daily_cashes_yesterday, title: "Ontem: #{@daily_cashes_yesterday.sum(:amount)}"} %>
  <%= render partial: "daily_cashes", locals: {daily_cashes: @daily_cashes_week, title: "Semana: #{@daily_cashes_week.sum(:amount)}"} %>
</div>