config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :daily_cashes
  resources :pre_sale_products
  resources :pre_sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :street_jobs
  resources :clients
  resources :products
  resources :distributors

  root 'dashboard#index'

end

app/models/pre_sale.rb
class PreSale < ActiveRecord::Base
  enum status: [ :with_us, :with_client, :converted_into_sale, :returned, :absent_client, :return_other_day ]
  belongs_to :client
  has_many :pre_sale_products, dependent: :destroy
  has_many :products, through: :pre_sale_products
  has_many :sales
  accepts_nested_attributes_for :pre_sale_products, allow_destroy: true, reject_if: proc { |attributes| attributes['product_name'].blank? || attributes['quantity'].blank? }
  delegate :name, to: :client, prefix: true, allow_nil: true
  attr_writer :client_name

  validates :client_name, :receive_pre_sale_at, :status, presence: true

  before_validation :set_client_by_name
  after_save :workflow_sale

  def workflow_sale
    if self.converted_into_sale?
      sale = Sale.new(client_id: self.client.id, pre_sale_id: self.id,
        sell_at: Time.now,
        payment_division: 1,
        payment_division_sell_price: self.pre_sale_products.to_a.sum{|t| t.price * t.quantity}
      )
      sale.save(validate: false)
      self.pre_sale_products.each do |pre_sale_product|
        sale.sale_products.build(product_id: pre_sale_product.product.id, price: pre_sale_product.price, quantity: pre_sale_product.quantity, detail: pre_sale_product.detail).save(validate: false)
      end
    end
  end

  def self.send_today
    PreSale.where(status: PreSale.statuses_for_send_today).where("send_pre_sale_at <= ?", Date.today.end_of_day)
  end

  def self.receive_today
    PreSale.where(status: PreSale.statuses_for_receive_today).where("receive_pre_sale_at <= ?", Date.today)
  end

  def self.statuses_for_send_today
    [ PreSale.statuses[:with_us] ]
  end

  def self.statuses_for_receive_today
    [ PreSale.statuses[:with_client], PreSale.statuses[:absent_client], PreSale.statuses[:return_other_day] ]
  end

  def save_and_schedule
    if save
      schedule_send_pre_sale
      schedule_receive_pre_sale
    end
  end

  def update_and_schedule(values)
    if update(values)
      schedule_send_pre_sale
      schedule_receive_pre_sale
    end
  end

  def self.send_pre_sale_emails_at_date(date = Date.today)
    PreSale.where(status: PreSale.statuses_for_send_today).where("send_pre_sale_at <= ?", Date.today.end_of_day).each do |pre_sale|
      Notifier.delay.send_pre_sale(pre_sale)
    end
  end

  def self.receive_pre_sale_emails_at_date(date = Date.today)
    PreSale.where(status: PreSale.statuses_for_receive_today).where("receive_pre_sale_at <= ?", Date.today.end_of_day).each do |pre_sale|
      Notifier.delay.receive_pre_sale(pre_sale)
    end
  end

  def name
    "#{self.client_name} - #{self.products.pluck(:name).to_sentence}"
  end

  protected

  def set_client_by_name
    self.client = Client.find_or_create_by(name: @client_name) unless @client_name.blank?
  end

  def schedule_receive_pre_sale
    if self.receive_pre_sale_at >= Date.today.beginning_of_day && self.receive_pre_sale_at <= Date.today.end_of_day
      Notifier.delay.receive_pre_sale(self)
    end
    true
  end

  def schedule_send_pre_sale
    return true if self.send_pre_sale_at.blank?
    if self.send_pre_sale_at >= Date.today.beginning_of_day && self.send_pre_sale_at <= Date.today.end_of_day
      Notifier.delay.send_pre_sale(self)
    end
    true
  end
end

app/controllers/pre_sales_controller.rb
class PreSalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pre_sale, only: [:show, :edit, :update, :destroy, :update_status]
  autocomplete :client, :name, full: true, extra_data: [:work]
  autocomplete :product, :name, full: true

  # GET /pre_sales
  # GET /pre_sales.json
  def index
    @pre_sales = PreSale.all
  end

  # GET /pre_sales/1
  # GET /pre_sales/1.json
  def show
  end

  # GET /pre_sales/new
  def new
    @pre_sale = PreSale.new(receive_pre_sale_at: Date.today + 3.days)
  end

  # GET /pre_sales/1/edit
  def edit
  end

  def update_status
    @pre_sale.status = params[:status]
    @pre_sale.save
    redirect_by_status(@pre_sale)
  end

  # POST /pre_sales
  # POST /pre_sales.json
  def create
    @pre_sale = PreSale.new(pre_sale_params)

    respond_to do |format|
      if @pre_sale.save_and_schedule
        format.html { redirect_to @pre_sale, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @pre_sale }
      else
        format.html { render :new }
        format.json { render json: @pre_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pre_sales/1
  # PATCH/PUT /pre_sales/1.json
  def update
    respond_to do |format|
      if @pre_sale.update_and_schedule(pre_sale_params)
        format.html { redirect_to @pre_sale, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :ok, location: @pre_sale }
      else
        format.html { render :edit }
        format.json { render json: @pre_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_sales/1
  # DELETE /pre_sales/1.json
  def destroy
    @pre_sale.destroy
    respond_to do |format|
      format.html { redirect_to pre_sales_url, notice: 'Operação realizada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pre_sale
      @pre_sale = PreSale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pre_sale_params
      params.require(:pre_sale).permit(:client_id, :client_name, :annotation, :receive_pre_sale_at,
        :send_pre_sale_at, :payment_method, :status,
        pre_sale_products_attributes: [:id, :product_name, :detail, :price, :quantity, :_destroy])
    end

    def redirect_by_status(pre_sale)
      if pre_sale.absent_client? || pre_sale.return_other_day?
        redirect_to edit_pre_sale_path(pre_sale), alert: "Reveja as datas de Envio e Recebimento"
      elsif pre_sale.converted_into_sale? && pre_sale.sales.count > 0
        redirect_to edit_sale_path(pre_sale.sales.last), notice: "Conversão em venda feita com sucesso. Termine de completar a venda"
      else
        redirect_to pre_sale_path(pre_sale), notice: "Situação atualizada com sucesso"
      end
    end
end

app/helpers/pre_sales_helper.rb
module PreSalesHelper
  def pre_sale_statuses_options
    pre_sale_statuses.map do |status, text|
      [text, status]
    end
  end

  def pre_sale_statuses
    statuses = {}
    PreSale.statuses.each do |status, code|
      statuses[status.to_sym] = I18n.t("activerecord.attributes.pre_sale.statuses.#{status}")
    end
    statuses
  end

  def pre_sale_status(status)
    pre_sale_statuses[status.to_sym]
  end
end

app/views/pre_sales/_form.html.erb
<%= simple_nested_form_for @pre_sale, wrapper: :vertical_input_group, :html => { :class => 'vertical-horizontal' } do |f| %>
  <%= f.input :client_name, as: :string, input_html: {data: { autocomplete: autocomplete_client_name_pre_sales_path }} %>
  <%= error_span(@pre_sale[:client_id]) %>
  <div class="well">
    <h4>Produtos</h4>
    <table class="table table-striped table-bordered" id="pre_sale_products">
      <thead>
        <tr>
          <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:product) %></th>
          <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:detail) %></th>
          <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:price) %></th>
          <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:quantity) %></th>
          <th class="col-sm-2"><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <%= f.fields_for :pre_sale_products, :wrapper => false do |pre_sale_product_form| %>
      <tr class="fields">
        <td><%= pre_sale_product_form.text_field :product_name, data: { autocomplete: autocomplete_product_name_pre_sales_path } %></td>
        <td><%= pre_sale_product_form.text_field :detail %></td>
        <td><%= pre_sale_product_form.text_field :price %></td>
        <td><%= pre_sale_product_form.text_field :quantity %></td>
        <td><%= pre_sale_product_form.link_to_remove "Remover", class: 'btn btn-danger btn-xs' %></td>
      </tr>
      <% end %>
    </table>
    <p><%= f.link_to_add "Adicionar produto", :pre_sale_products, class: 'btn btn-xs btn-primary', data: { target: "#pre_sale_products" } %></p>
  </div>

  <%= f.input :send_pre_sale_at, include_blank: true%>
  <%= error_span(@pre_sale[:send_pre_sale_at]) %>
  <%= f.input :receive_pre_sale_at %>
  <%= error_span(@pre_sale[:receive_pre_sale_at]) %>
  <%= f.input :payment_method, collection: sale_payment_methods_options %>
  <%= error_span(@pre_sale[:payment_method]) %>
  <%= f.input :annotation %>
  <%= error_span(@pre_sale[:annotation]) %>
  <%= f.input :status, collection: pre_sale_statuses_options %>
  <%= error_span(@pre_sale[:status]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pre_sales_path, :class => 'btn btn-default' %>
<% end %>

app/views/pre_sales/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => PreSale.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pre_sales/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => PreSale.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= PreSale.human_attribute_name(:id) %></th>
      <th><%= PreSale.human_attribute_name(:client_id) %></th>
      <th><%= PreSale.human_attribute_name(:send_pre_sale_at) %></th>
      <th><%= PreSale.human_attribute_name(:receive_pre_sale_at) %></th>
      <th><%= PreSale.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pre_sales.each do |pre_sale| %>
      <tr>
        <td><%= link_to pre_sale.id, pre_sale_path(pre_sale) %></td>
        <td><%= pre_sale.client.name %></td>
        <td><%= l(pre_sale.send_pre_sale_at, format: :long) if pre_sale.send_pre_sale_at %></td>
        <td><%= l(pre_sale.receive_pre_sale_at, format: :long) %></td>
        <td><%= pre_sale_status pre_sale.status %></td>
        <td>
          <div class="btn-group">
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      pre_sale, :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pre_sale_path(pre_sale), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pre_sale_path(pre_sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pre_sale_path,
            :class => 'btn btn-primary' %>

app/views/pre_sales/new.html.erb
<%- model_class = PreSale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => PreSale.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pre_sales/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => PreSale.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= PreSale.human_attribute_name(:client) %>:</strong></dt>
  <dd><%= @pre_sale.client.name %></dd>
  <dt><strong><%= PreSale.human_attribute_name(:send_pre_sale_at) %>:</strong></dt>
  <dd><%= l(@pre_sale.send_pre_sale_at, format: :long) if @pre_sale.send_pre_sale_at %></dd>
  <dt><strong><%= PreSale.human_attribute_name(:receive_pre_sale_at) %>:</strong></dt>
  <dd><%= l @pre_sale.receive_pre_sale_at, format: :long %></dd>
  <dt><strong><%= PreSale.human_attribute_name(:payment_method) %>:</strong></dt>
  <dd><%= @pre_sale.payment_method %></dd>
  <dt><strong><%= PreSale.human_attribute_name(:annotation) %>:</strong></dt>
  <dd><%= @pre_sale.annotation %></dd>
  <dt><strong><%= PreSale.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= pre_sale_status @pre_sale.status %></dd>
</dl>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:product) %></th>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:detail) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:price) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:quantity) %></th>
    </tr>
  </thead>
  <% @pre_sale.pre_sale_products.each do |pre_sale_product| %>
  <tr>
    <td><%= pre_sale_product.product.name %></td>
    <td><%= pre_sale_product.detail %></td>
    <td><%= pre_sale_product.price %></td>
    <td><%= pre_sale_product.quantity %></td>
  </tr>
  <% end %>
</table>
<div class="well">
<h3>Aproveite para atualizar os dados do cliente</h3>
<%= simple_form_for @pre_sale.client, wrapper: :horizontal_input_group, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@pre_sale.client[:name]) %>
  <%= f.input :phone %>
  <%= error_span(@pre_sale.client[:phone]) %>
  <%= f.input :mobile %>
  <%= error_span(@pre_sale.client[:mobile]) %>
  <%= f.input :email %>
  <%= error_span(@pre_sale.client[:email]) %>
  <%= f.input :work %>
  <%= error_span(@pre_sale.client[:work]) %>
  <%= f.input :work_address %>
  <%= error_span(@pre_sale.client[:work_address]) %>
  <%= f.input :work_phone %>
  <%= error_span(@pre_sale.client[:work_phone]) %>
  <%= f.input :best_day %>
  <%= error_span(@pre_sale.client[:best_day]) %>

  <div class="form-actions col-sm-offset-3">
    <%= f.button :submit, :class => 'btn' %>
  </div>
<% end %>
</div>

<div class="btn-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
                pre_sales_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_pre_sale_path(@pre_sale), :class => 'btn btn-default' %>
  <% pre_sale_statuses.each do |status, text| %>
    <%= link_to text,
                update_status_pre_sale_path(@pre_sale, status: status), :class => 'btn btn-primary' %>
  <% end -%>
</div>