config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :daily_cashes
  resources :pre_sale_products
  resources :pre_sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :street_jobs
  resources :clients
  resources :products
  resources :distributors

  root 'dashboard#index'

end

app/views/notifier/receive_pre_sale.html.erb
<h1><%= I18n.t('notifier.receive_pre_sale.subject')%></h1>

<p>
  O condicional <strong><u><%= link_to "##{@pre_sale.id}", pre_sale_url(@pre_sale) %></u></strong> vence dia <strong><u><%= I18n.l(@pre_sale.receive_pre_sale_at, format: :long) %></u></strong><br />
  Os dados para entrar em contato com o cliente <strong><u><%= @pre_sale.client.name %></u></strong> são:
</p>

<div class="well">
  <dl class="dl-horizontal">
    <dt><strong><%= Client.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @pre_sale.client.name %></dd>
    <dt><strong><%= Client.human_attribute_name(:phone) %>:</strong></dt>
    <dd><%= @pre_sale.client.phone %></dd>
    <dt><strong><%= Client.human_attribute_name(:mobile) %>:</strong></dt>
    <dd><%= @pre_sale.client.mobile %></dd>
    <dt><strong><%= Client.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @pre_sale.client.email %></dd>
    <dt><strong><%= Client.human_attribute_name(:work) %>:</strong></dt>
    <dd><%= @pre_sale.client.work %></dd>
    <dt><strong><%= Client.human_attribute_name(:work_address) %>:</strong></dt>
    <dd><%= @pre_sale.client.work_address %></dd>
    <dt><strong><%= Client.human_attribute_name(:work_phone) %>:</strong></dt>
    <dd><%= @pre_sale.client.work_phone %></dd>
    <dt><strong><%= Client.human_attribute_name(:best_day) %>:</strong></dt>
    <dd><%= @pre_sale.client.best_day %></dd>
  </dl>
</div>

<h2>Produtos</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:product) %></th>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:detail) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:price) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:quantity) %></th>
    </tr>
  </thead>
  <% @pre_sale.pre_sale_products.each do |pre_sale_product| %>
  <tr>
    <td><%= pre_sale_product.product.name %></td>
    <td><%= pre_sale_product.detail %></td>
    <td><%= pre_sale_product.price %></td>
    <td><%= pre_sale_product.quantity %></td>
  </tr>
  <% end %>
</table>

app/views/notifier/receive_pre_sale.text.erb
Notifier#receive_pre_sale

<%= @greeting %>, find me in app/views/notifier/receive_pre_sale.text.erb

app/views/notifier/send_pre_sale.html.erb
<h1><%= I18n.t('notifier.send_pre_sale.subject')%></h1>

<p>
  O condicional <u><strong><%= link_to "##{@pre_sale.id}", pre_sale_url(@pre_sale) %></strong></u> deve ser enviado ao cliente dia <strong><u><%= I18n.l(@pre_sale.send_pre_sale_at, format: :long) %></u></strong><br />
  Os dados para entrar em contato com o cliente <strong><u><%= @pre_sale.client.name %></u></strong> são:
</p>

<div class="well">
  <dl class="dl-horizontal">
    <dt><strong><%= Client.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @pre_sale.client.name %></dd>
    <dt><strong><%= Client.human_attribute_name(:phone) %>:</strong></dt>
    <dd><%= @pre_sale.client.phone %></dd>
    <dt><strong><%= Client.human_attribute_name(:mobile) %>:</strong></dt>
    <dd><%= @pre_sale.client.mobile %></dd>
    <dt><strong><%= Client.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @pre_sale.client.email %></dd>
    <dt><strong><%= Client.human_attribute_name(:work) %>:</strong></dt>
    <dd><%= @pre_sale.client.work %></dd>
    <dt><strong><%= Client.human_attribute_name(:work_address) %>:</strong></dt>
    <dd><%= @pre_sale.client.work_address %></dd>
    <dt><strong><%= Client.human_attribute_name(:work_phone) %>:</strong></dt>
    <dd><%= @pre_sale.client.work_phone %></dd>
    <dt><strong><%= Client.human_attribute_name(:best_day) %>:</strong></dt>
    <dd><%= @pre_sale.client.best_day %></dd>
  </dl>
</div>


<h2>Produtos</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:product) %></th>
      <th class="col-sm-3"><%= PreSaleProduct.human_attribute_name(:detail) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:price) %></th>
      <th class="col-sm-2"><%= PreSaleProduct.human_attribute_name(:quantity) %></th>
    </tr>
  </thead>
  <% @pre_sale.pre_sale_products.each do |pre_sale_product| %>
  <tr>
    <td><%= pre_sale_product.product.name %></td>
    <td><%= pre_sale_product.detail %></td>
    <td><%= pre_sale_product.price %></td>
    <td><%= pre_sale_product.quantity %></td>
  </tr>
  <% end %>
</table>

app/views/notifier/send_pre_sale.text.erb
Notifier#send_pre_sale

<%= @greeting %>, find me in app/views/notifier/send_pre_sale.text.erb

app/views/notifier/street_job.html.erb
<h1><%= I18n.t('notifier.street_job.subject')%></h1>

<p>
  Foi criada a tarefa diária <u><strong><%= link_to "##{@street_job.id}", street_job_url(@street_job) %></strong></u> para o dia <strong><u><%= I18n.l(@street_job.scheduled_at, format: :long) %></u></strong><br />
  As informações da mesma são:
</p>

<div class="well">
  <dl class="dl-horizontal">
    <dt><strong><%= StreetJob.human_attribute_name(:jobable_id) %>:</strong></dt>
    <dd><%= @street_job.jobable_id %></dd>
    <dt><strong><%= StreetJob.human_attribute_name(:jobable_type) %>:</strong></dt>
    <dd><%= @street_job.jobable_type %></dd>
    <dt><strong><%= StreetJob.human_attribute_name(:annotation) %>:</strong></dt>
    <dd><%= @street_job.annotation %></dd>
    <dt><strong><%= StreetJob.human_attribute_name(:scheduled_at) %>:</strong></dt>
    <dd><%= l @street_job.scheduled_at, format: :long %></dd>
    <dt><strong><%= StreetJob.human_attribute_name(:operation_type) %>:</strong></dt>
    <dd><%= street_job_operation_type @street_job.operation_type %></dd>
    <dt><strong><%= StreetJob.human_attribute_name(:status) %>:</strong></dt>
    <dd><%= street_job_status @street_job.status %></dd>
  </dl>
</div>