config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :daily_cashes
  resources :pre_sale_products
  resources :pre_sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :sales do
    get :autocomplete_client_name, :on => :collection
    get :autocomplete_product_name, :on => :collection
    get :update_status, on: :member
  end
  resources :street_jobs
  resources :clients
  resources :products
  resources :distributors

  root 'dashboard#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  enum status: [ :finished_and_received, :finished_and_not_received, :returned ]
  enum payment_method: [ :creditcard, :money, :check, :online_transfer, :installment_sales ]
  has_many :daily_cashes
  has_many :sale_products, dependent: :destroy
  has_many :products, through: :sale_products
  accepts_nested_attributes_for :sale_products, allow_destroy: true, reject_if: proc { |attributes| attributes['product_name'].blank? || attributes['quantity'].blank? }
  belongs_to :sale
  belongs_to :pre_sale
  belongs_to :user
  belongs_to :client
  after_create :receive_payment

  delegate :name, to: :client, prefix: true, allow_nil: true
  attr_writer :client_name

  validates :client_name, :user_id, :status, :payment_division, :payment_division_sell_price, :payment_method, presence: true

  def receive_payment
    if self.finished_and_received? && self.money?
      self.daily_cashes.money.build(amount: self.amount_sold).save
    end
  end

  def self.to_receive
    Sale.where(status: Sale.statuses[:finished_and_not_received])
  end

  def amount
    self.sale_products.to_a.sum{|t| t.price * t.quantity}
  rescue
    0
  end

  def amount_sold
    (self.payment_division * self.payment_division_sell_price) + self.money_on_create.to_f
  rescue
    0
  end

  def offer_to_client
    amount - self.amount_sold
  end

  def name
    "#{self.client_name} (#{self.amount_sold}) - #{self.products.pluck(:name).to_sentence}"
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  autocomplete :client, :name, full: true, extra_data: [:work]
  autocomplete :product, :name, full: true

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new(payment_division: 1)
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Operação realizada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:pre_sale_id, :user_id, :client_id, :annotation, :payment_method, :payment_division,
        :best_day_to_receive, :payment_division_sell_price, :discount, :status, :sell_at, :sale_id, :money_on_create,
        sale_products_attributes: [:id, :product_name, :detail, :price, :quantity, :_destroy])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
  def sale_statuses_options
    sale_statuses.sort_by{|t,text| text}.to_h.map do |status, text|
      [text, status]
    end
  end

  def sale_statuses
    statuses = {}
    Sale.statuses.each do |status, code|
      statuses[status.to_sym] = I18n.t("activerecord.attributes.sale.statuses.#{status}")
    end
    statuses
  end

  def sale_status(status)
    sale_statuses[status.to_sym]
  rescue
    '-'
  end

  def sale_payment_methods_options
    sale_payment_methods.sort_by{|t,text| text}.to_h.map do |payment_method, text|
      [text, payment_method]
    end
  end

  def sale_payment_methods
    payment_methods = {}
    Sale.payment_methods.each do |payment_method, code|
      payment_methods[payment_method.to_sym] = I18n.t("activerecord.attributes.sale.payment_methods.#{payment_method}")
    end
    payment_methods
  end

  def sale_payment_method(payment_method)
    sale_payment_methods[payment_method.to_sym]
  rescue
    '-'
  end

  def sale_tr_class(sale)
    if sale.finished_and_received?
      'success'
    elsif sale.finished_and_not_received?
      'warning'
    else
      'danger'
    end
  end
end

app/views/sales/_form.html.erb
<%= simple_nested_form_for @sale, wrapper: :vertical_input_group, :html => { :class => 'vertical-horizontal' } do |f| %>
  <%= f.association :user, collection: User.all %>
  <%= error_span(@sale[:user_id]) %>
  <%= f.association :client, collection: Client.order(:name) %>
  <%= error_span(@sale[:client_id]) %>
  <%= f.association :sale, collection: (f.object.client_id ? Sale.finished_and_not_received.where(client_id: f.object.client_id).order(:sell_at) : []) %>
  <%= error_span(@sale[:sale_id]) %>
  <%= f.input :sell_at %>
  <%= error_span(@sale[:sell_at]) %>
  <%= f.input :best_day_to_receive, input_html: {min: 1, max: 31} %>
  <%= error_span(@sale[:best_day_to_receive]) %>
  <div class="well">
    <h4>Produtos</h4>
    <table class="table table-striped table-bordered" id="sale_products">
      <thead>
        <tr>
          <th class="col-sm-3"><%= SaleProduct.human_attribute_name(:product) %></th>
          <th class="col-sm-3"><%= SaleProduct.human_attribute_name(:detail) %></th>
          <th class="col-sm-2"><%= SaleProduct.human_attribute_name(:price) %></th>
          <th class="col-sm-2"><%= SaleProduct.human_attribute_name(:quantity) %></th>
          <th class="col-sm-2"><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <%= f.fields_for :sale_products, :wrapper => false do |sale_product_form| %>
      <tr class="fields">
        <td><%= sale_product_form.text_field :product_name, data: { autocomplete: autocomplete_product_name_sales_path } %></td>
        <td><%= sale_product_form.text_field :detail %></td>
        <td><%= sale_product_form.text_field :price %></td>
        <td><%= sale_product_form.text_field :quantity %></td>
        <td><%= sale_product_form.link_to_remove "Remover", class: 'btn btn-danger btn-xs' %></td>
      </tr>
      <% end %>
    </table>
    <p><%= f.link_to_add "Adicionar produto", :sale_products, class: 'btn btn-xs btn-primary', data: { target: "#sale_products" } %></p>
  </div>

  <%= f.input :money_on_create %>
  <%= error_span(@sale[:money_on_create]) %>
  <%= f.input :discount, input_html: {max: 20, min: 0} %>
  <%= error_span(@sale[:discount]) %>
  <%= f.input :payment_division, input_html: {min: 1, max: 12} %>
  <%= error_span(@sale[:payment_division]) %>
  <%= link_to "Calcular Parcelas", '#', class: 'btn btn-primary' %>
  <hr />
  <%= f.input :payment_division_sell_price %>
  <%= error_span(@sale[:payment_division_sell_price]) %>
  <%= f.input :annotation %>
  <%= error_span(@sale[:annotation]) %>
  <%= f.input :payment_method, collection: sale_payment_methods_options %>
  <%= error_span(@sale[:payment_method]) %>
  <%= f.input :status, collection: sale_statuses_options %>
  <%= error_span(@sale[:status]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn btn-default' %>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Sale.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Sale.human_attribute_name(:id) %></th>
      <th><%= Sale.human_attribute_name(:user_id) %></th>
      <th><%= Sale.human_attribute_name(:client_id) %></th>
      <th><%= Sale.human_attribute_name(:payment_method) %></th>
      <th><%= Sale.human_attribute_name(:money_on_create) %></th>
      <th><%= Sale.human_attribute_name(:payment_division) %></th>
      <th><%= Sale.human_attribute_name(:payment_division_sell_price) %></th>
      <th><%= Sale.human_attribute_name(:amount_sold) %></th>
      <th><%= Sale.human_attribute_name(:status) %></th>
      <th><%= Sale.human_attribute_name(:sell_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.user.try(:name) %></td>
        <td><%= sale.client_name %></td>
        <td><%= sale_payment_method sale.payment_method %></td>
        <td><%= sale.money_on_create %></td>
        <td><%= sale.payment_division %></td>
        <td><%= sale.payment_division_sell_price %></td>
        <td><%= sale.amount_sold %></td>
        <td><%= sale_status sale.status %></td>
        <td><u><strong><%=l sale.sell_at if sale.sell_at %></strong></u></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      sale, :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Sale.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <% if @sale.pre_sale %>
  <dt><strong><%= Sale.human_attribute_name(:pre_sale_id) %>:</strong></dt>
  <dd><%= @sale.pre_sale.name %></dd>
  <% end -%>
  <dt><strong><%= Sale.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @sale.user.try(:email) %></dd>
  <dt><strong><%= Sale.human_attribute_name(:client_id) %>:</strong></dt>
  <dd><%= @sale.client_name %></dd>
  <dt><strong><%= Sale.human_attribute_name(:sell_at) %>:</strong></dt>
  <dd><%= l @sale.sell_at, format: :long %></dd>
  <dt><strong><%= Sale.human_attribute_name(:best_day_to_receive) %>:</strong></dt>
  <dd><%= l(@sale.best_day_to_receive, format: :long) if @sale.best_day_to_receive %></dd>
  <dt><strong><%= Sale.human_attribute_name(:annotation) %>:</strong></dt>
  <dd><%= @sale.annotation %></dd>
  <dt><strong><%= Sale.human_attribute_name(:payment_method) %>:</strong></dt>
  <dd><%= sale_payment_method @sale.payment_method %></dd>
  <dt><strong><%= Sale.human_attribute_name(:money_on_create) %>:</strong></dt>
  <dd><%= @sale.money_on_create %></dd>
  <dt><strong><%= Sale.human_attribute_name(:payment_division) %>:</strong></dt>
  <dd><%= @sale.payment_division %></dd>
  <dt><strong><%= Sale.human_attribute_name(:payment_division_sell_price) %>:</strong></dt>
  <dd><%= @sale.payment_division_sell_price %></dd>
  <dt><strong><%= Sale.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @sale.discount %></dd>
  <dt><strong><%= Sale.human_attribute_name(:amount_sold) %>:</strong></dt>
  <dd><%= @sale.amount_sold %></dd>
  <dt><strong><%= Sale.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @sale.amount %></dd>
  <dt><strong title="<%= Sale.human_attribute_name(:offer_to_client) %>"><%= Sale.human_attribute_name(:offer_to_client) %>:</strong></dt>
  <dd><%= @sale.offer_to_client %></dd>
  <dt><strong><%= Sale.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= sale_status @sale.status %></dd>
</dl>

<div class="btn-group">
<%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn btn-default' %>
<% unless @sale.finished_and_received? %>
  <%= link_to t('Lançar recebimento'), new_daily_cash_path(sale_id: @sale.id), :class => 'btn btn-primary' %>
<%   end -%>
</div>